// Code generated by MockGen. DO NOT EDIT.
// Source: blog/app/usecase (interfaces: ShortURLGateway)

// Package gatewaymock is a generated GoMock package.
package gatewaymock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortURLGateway is a mock of ShortURLGateway interface.
type MockShortURLGateway struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLGatewayMockRecorder
}

// MockShortURLGatewayMockRecorder is the mock recorder for MockShortURLGateway.
type MockShortURLGatewayMockRecorder struct {
	mock *MockShortURLGateway
}

// NewMockShortURLGateway creates a new mock instance.
func NewMockShortURLGateway(ctrl *gomock.Controller) *MockShortURLGateway {
	mock := &MockShortURLGateway{ctrl: ctrl}
	mock.recorder = &MockShortURLGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLGateway) EXPECT() *MockShortURLGatewayMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockShortURLGateway) CreateShortURL(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockShortURLGatewayMockRecorder) CreateShortURL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockShortURLGateway)(nil).CreateShortURL), arg0)
}
